### ISSUE TITLE
The collecting process keeps hanging

### ISSUE THREAD

**Issue by desbest** [HuiiBuh/InstagramDownloader#209]
# The collecting process keeps hanging

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to URL 'https://www.instagram.com/slowlyapp/
2. Click on download all images button
3. It hangs at the end of the "collected all X posts" message and then never proceeds to downloading

**Expected behaviour**
It should proceed to downloading. This happens whether logged in or logged out, but if logged out then the second screenshot applies.

**Screenshots**
![ig downloader froze 1](https://user-images.githubusercontent.com/1139316/121904192-e33ceb00-cd20-11eb-825c-e643638b8330.png)
![ig downloader froze 2](https://user-images.githubusercontent.com/1139316/121904206-e506ae80-cd20-11eb-87ee-623111fd36e0.png)

**Device (please complete the following information):**
- Resolution: 1366x768
- Browser Firefox 89
- Operating System: Windows 10 21H1
- Extension Version: 4.4.6

**Additional context**
Having "extended tracking protection" on or off doesn't solve this bug.

**Comment by desbest** [comment]
I found a workaround for this by installing Ublock Origin and Canvas Blocker both at the same time. However before installing them you should delete all cookies to do with facebook, instagram and their cdn's.

- facebook.com
- fb.com
- instagram.com
- fbcdn.net
- cdninstagram.com

**Comment by desbest** [comment]
I found a workaround for this by installing [Ublock Origin](https://addons.mozilla.org/en-GB/firefox/addon/ublock-origin/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) and [Canvas Blocker](https://addons.mozilla.org/en-GB/firefox/addon/canvasblocker/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) both at the same time. However before installing them you should delete all cookies to do with facebook, instagram and their cdn's.

- facebook.com
- fb.com
- instagram.com
- fbcdn.net
- cdninstagram.com

Afterwards if you are already logged in, logout your account and do the mass downloading while logged out.

**Comment by HuiiBuh** [comment]
I think the problem is the loading spinner which does not disappear and therefore my extension does not know, that no additional content gets loaded. Just press the *stop download*/*stop collecting images* button and the download will continue...

**Comment by desbest** [comment]
A new version of your extension got released today so I'll install it and disable any content, advert and tracking blockers, and see if I still experience the same problem in future.

**Comment by desbest** [comment]
The same error is happening again. When I click "stop collecting images" nothing happens.

**Comment by HuiiBuh** [comment]
Do you have any other extensions installed?
Because it seems like you are the only person who has that problem.

Are there any errors in the console?

**Comment by desbest** [comment]
I disabled all my extensions and it still doesn't work.

> SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

![ig downloader error](https://user-images.githubusercontent.com/1139316/124985658-90f69d80-e032-11eb-9fee-7107033f663b.png)

**Comment by folknor** [comment]
Exactly the same error for me. Nothing happens when I click "stop collecting and download", and same error in the console as the previous poster.

**Comment by desbest** [comment]
There's a new version of this extension released so I'll see if I continue to have the same problem with the new version.

Highlights are


 > * New alert design
 > * New bulk download design
 > * Better obfuscation, so Instagram does not detect that you are using a downloader
 > * Improved mutation observer, so events don't get fired so fast

**Comment by HuiiBuh** [comment]
That Is unfortunate.
Can you try to debug the problem?
Because it looks to. me like the Jsonparse error is not from. me. At least I think that, because there is no stack trace associated with it.

**Comment by desbest** [comment]
After upgrading to the latest version I'm getting the same error in 4.5.0

> SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

![instagram downloader freezes at collected 2](https://user-images.githubusercontent.com/1139316/130060875-2e337edd-2931-4084-98cd-8625a89be357.png)

**Comment by desbest** [comment]
Now I'm getting another error.

> Error: Promised response from onMessage listener went out of scope
Line 121 column 89

```        webextension_polyfill_ts__WEBPACK_IMPORTED_MODULE_0__.browser.runtime.onMessage.addListener(BackgroundMessageHandler_1.onMessage);
```

**Comment by desbest** [comment]
It seems like with version 4.5.0 and 4.5.1 some progress is made in the sense that moves past the collecting images with the lightbox step to move into the downloading images step without the lightbox. This is an improvement.

However the bug I've been happening in the above post (repeated below) upon further investigation it appears that the bug is isolated to when a stark minority specific of instagram profiles are chosen for a bulk download.

Would it be good idea for me to compile a list of profiles where the bulk download process fails, so you can reproduce the bug?

**Comment by HuiiBuh** [comment]
Yes, if you can send me the profiles of the people where ist ist jot working I could fix the issue. 
Currently I cannot reproduce it

**Comment by Kilowog01** [comment]
karenbachini profile
![Capturar](https://user-images.githubusercontent.com/16064499/134092232-2ad00449-4ab7-4ad2-b339-0a61b2d3f8d3.PNG)

**Comment by roweger** [comment]
I experience this issue when InstagramDownloader comes across particular seemingly "restricted" posts. 

For example...

If you view this page, there are currently 11 reels displayed. 
https://www.instagram.com/mariarzolaa/reels/

But when attempting to view the individual page for some of those reels, Instagram returns the page:

> Sorry, this page isn't available.
> The link you followed may be broken, or the page may have been removed. Go back to Instagram. 

This occurs for me with:
https://www.instagram.com/reel/CRHi_pUh62w/
https://www.instagram.com/reel/CMfd_2bh7Qn/
https://www.instagram.com/reel/CRHi_pUh62w/

But all three of those are displayed on that page, and are viewable if you just click them directly from the reels page (and don't try to open them in a new tab.)

My first thought is that this behavior is something like an age restriction to limit the visibility of "inappropriate" content...but since there doesn't appear to be a way to set one's age in the user profile, it's possible IG just disables the viewability of particular posts outside of the profile itself (i.e. you can only click them directly on the profile, the direct link doesn't work.)

It appears that when InstagramDownloader comes across one of these kind of posts, since the post doesn't load normally, the application just freezes.

This behavior should be able to be recreated by running a batch download on that page:
https://www.instagram.com/mariarzolaa/reels/

Currently there are 11 reels, and the 5th one from the top is one of those restricted posts, and that's exactly where InstagramDownloader freezes and you can't click out of it.

Would it be possible to have the app continue one to the next one when it comes across one of these and it fails to download? Ideally InstagramDownloader would also collect these restricted links so the user could have a list of which posts weren't downloaded.

**Comment by HuiiBuh** [comment]
@roweger thanks for your detailed writeup. This could be the case. I will have a look at it during the next week

**Comment by desbest** [comment]
I'm getting another error on some "tagged" pages.

> TypeError: response.items is undefined **download-functions.ts:66:4**

**Comment by HuiiBuh** [comment]
Good news. 
Just fixed the bug. 
The next release will include the fix
