### ISSUE TITLE
problem with stories that opened from direct

### ISSUE THREAD

**Issue by MJamshidnejad** [HuiiBuh/InstagramDownloader#219]
Hello. First of all, I would like to thank you for this great app. When I open a story that someone sent to me, I can not download it. I should open the page and download it from the storyline of the page. Please fix this issue.

**Comment by HuiiBuh** [comment]
Hi I cannot reproduce the issue. 
Please provide the following information

---

# Important: Issues without the following information will be closed

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to URL 'https://www.instagram.com/world_record_egg/'
2. Click on '....'
3. See error

**Expected behaviour**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Device (please complete the following information):**
- Resolution: [e.g 2K]
- Browser [e.g. chrome, firefox]
- Extension Version [e.g. 4.0.1]

**Additional context**
Add any other context about the problem here.
