### ISSUE TITLE
How can I contribute?

### ISSUE THREAD

**Issue by christoarmani** [HuiiBuh/InstagramDownloader#283]
I am new to Github and I would like to fix a bug where videos from stories aren't named correctly. I have successfully cloned the repo. How I can import/create an offline copy for me to debug the issue? Chrome says I need a manifest,json and options.html file. Is there another way?

**Comment by katsos** [comment]
First of all, you have to open a new issue that describes the bug, the actual and the expected behavior.

Then start from here
1. https://github.com/HuiiBuh/InstagramDownloader#building
2. https://developer.chrome.com/docs/extensions/mv3/getstarted/

The first one says how to develop the code with watch mode on (which is very useful)
and the second describes how chrome extensions work.
You should be able to toggle developer mode on in your chrome and then "load unpacked" the "src" folder of the repository.

**Comment by christoarmani** [comment]
To be clear, I did raise the bug and it was closed. 

To state the issue again:

Video stories are not being saved as Instagram's internal file structure.

Actual (current behavior):
bugatti_794C6ECAF345B171AB704731CE2F4DA6_video_dashinit.mp4

Expected (behavior):
bugatti_278097595_521945046005591_5951759409346458410_n.mp4

**Comment by HuiiBuh** [comment]
If you want to fix #265 you can just create a PR. I would be happy to merge it.
Otherwise I will not fix this issue because I lack the time...
